package pipeline

var styleName = map[string]string{
	"Ani":   "Animal",
	"Ani2":  "Animal",
	"Apr":   "Apron",
	"Apr2":  "Apron",
	"Arm":   "Army",
	"Arm2":  "Army",
	"Boh":   "Bohemia",
	"Boh2":  "Bohemia",
	"Bri":   "Britain",
	"Bri2":  "Britain",
	"Bun":   "Bunny",
	"Bun2":  "Bunny",
	"Che":   "Cheongsam",
	"Che2":  "Cheongsam",
	"Chi":   "Chinese Classical",
	"Chi2":  "Chinese Classical",
	"Chic":  "Chic",
	"Chic2": "Chic",
	"Dan":   "Dancer",
	"Dan2":  "Dancer",
	"Den":   "Denim",
	"Den2":  "Denim",
	"Dry":   "Dryad",
	"Dry2":  "Dryad",
	"Eur":   "European",
	"Eur2":  "European",
	"Eve":   "Evening Gown",
	"Eve2":  "Evening Gown",
	"Fai":   "Fairy",
	"Fai2":  "Fairy",
	"Flo":   "Floral",
	"Flo2":  "Floral",
	"Fut":   "Future",
	"Fut2":  "Future",
	"God":   "Goddess",
	"God2":  "Goddess",
	"Got":   "Gothic",
	"Got2":  "Gothic",
	"Har":   "Harajuku",
	"Har2":  "Harajuku",
	"Hin":   "Hindu",
	"Hin2":  "Hindu",
	"Hom":   "Homewear",
	"Hom2":  "Homewear",
	"Kim":   "Kimono",
	"Kim2":  "Kimono",
	"Lad":   "Lady",
	"Lad2":  "Lady",
	"Lol":   "Lolita",
	"Lol2":  "Lolita",
	"Mai":   "Maiden",
	"Mai2":  "Maiden",
	"Mod":   "Modern China",
	"Mod2":  "Modern China",
	"Mul":   "Multicultural",
	"Mul2":  "Multicultural",
	"Mus":   "Musician",
	"Mus2":  "Musician",
	"Nav":   "Navy",
	"Nav2":  "Navy",
	"Off":   "Office",
	"Off2":  "Office",
	"POP":   "POP",
	"POP2":  "POP",
	"Paj":   "Pajamas",
	"Paj2":  "Pajamas",
	"Par":   "Paramedics",
	"Par2":  "Paramedics",
	"Pet":   "Pet",
	"Pet2":  "Pet",
	"Pre":   "Preppy",
	"Pre2":  "Preppy",
	"Rai":   "Rain",
	"Rai2":  "Rain",
	"Rep":   "Republic of China",
	"Rep2":  "Republic of China",
	"Roc":   "Rock",
	"Roc2":  "Rock",
	"Sai":   "Sailor",
	"Sai2":  "Sailor",
	"Sho":   "Shower",
	"Sho2":  "Shower",
	"Spo":   "Sports",
	"Spo2":  "Sports",
	"Str":   "Street",
	"Str2":  "Street",
	"Sun":   "Sun Care",
	"Sun2":  "Sun Care",
	"Swi":   "Swimsuit",
	"Swi2":  "Swimsuit",
	"Swo":   "Swordsman",
	"Swo2":  "Swordsman",
	"Tra":   "Traditional",
	"Tra2":  "Traditional",
	"Uni":   "Unisex",
	"Uni2":  "Unisex",
	"Wed":   "Wedding",
	"Wed2":  "Wedding",
	"Win":   "Winter",
	"Win2":  "Winter",
	"Wor":   "Workwear",
	"Wor2":  "Workwear",
}

var styleAlias = map[string]string{
	"Future(未来系)":  "Future",
	"OL":           "Office",
	"Sun Care(防晒)": "Sun Care",
	"pop":          "POP",
	"中式古典":         "Chinese Classical",
	"中式现代":         "Modern China",
	"中性风":          "Unisex",
	"侠客联盟":         "Swordsman",
	"兔女郎":          "Bunny",
	"军装":           "Army",
	"冬装":           "Winter",
	"医务使者":         "Paramedics",
	"印度服饰":         "Hindu",
	"原宿系":          "Harajuku",
	"和风":           "Kimono",
	"哥特风":          "Gothic",
	"围裙":           "Apron",
	"大小姐":          "Lady",
	"女仆装":          "Maiden",
	"女神系":          "Goddess",
	"婚纱":           "Wedding",
	"学院系":          "Preppy",
	"小动物":          "Pet",
	"居家服":          "Homewear",
	"摇滚风":          "Rock",
	"旗袍":           "Cheongsam",
	"晚礼服":          "Evening Gown",
	"未来系":          "Future",
	"森女系列":         "Dryad",
	"欧式古典":         "European",
	"民国服饰":         "Republic of China",
	"民族风":          "Traditional",
	"沐浴":           "Shower",
	"波西米亚":         "Bohemia",
	"泳装":           "Swimsuit",
	"洛丽塔":          "Lolita",
	"海军风":          "Navy",
	"牛仔布":          "Denim",
	"睡衣":           "Pajamas",
	"碎花":           "Floral",
	"童话系":          "Fairy",
	"舞者":           "Dancer",
	"英伦":           "Britain",
	"运动系":          "Sports",
	"防晒":           "Sun Care",
	"雨季装备":         "Rain",
}

var styleOrder = []string{
	"Animal",
	"Apron",
	"Army",
	"Bohemia",
	"Britain",
	"Bunny",
	"Cheongsam",
	"Chic",
	"Chinese Classical",
	"Dancer",
	"Denim",
	"Dryad",
	"European",
	"Evening Gown",
	"Fairy",
	"Floral",
	"Future",
	"Goddess",
	"Gothic",
	"Harajuku",
	"Hindu",
	"Homewear",
	"Kimono",
	"Lady",
	"Lolita",
	"Maiden",
	"Modern China",
	"Multicultural",
	"Musician",
	"Navy",
	"Office",
	"POP",
	"Pajamas",
	"Paramedics",
	"Pet",
	"Preppy",
	"Rain",
	"Republic of China",
	"Rock",
	"Sailor",
	"Shower",
	"Sports",
	"Street",
	"Sun Care",
	"Swimsuit",
	"Swordsman",
	"Traditional",
	"Unisex",
	"Wedding",
	"Winter",
	"Workwear",
}
